language: node_js
node_js:
- '8'
before_deploy:
- npm run build
branches:
  only:
  - development
deploy:
  provider: pages
  target_branch: master
  skip_cleanup: true
  local_dir: dist
  github_token:
    secure: hcqlFgYJGCldWFbFgTcWMiBLYL9/YonXRJ3D0Jv2BRfjtn4qCPY1u8+IjS/VriaUmCvLgoWDNFe3vWg4O1b3rLsid1zfymCMHmVE6lAtKm/kAidGTJd/ojBz94lT2eS5rISJ4BSZTBoe3ppbxlYFjj493d+TREzRyL6XWMH1l1XLdK1fRj7ufVlxam3hvHcgkD1S4xVWaszZqNU5AtAgtlyZXDNA/6Ma3/2yheiTmrxY8rZtUFBCe8KN0wNilJ2zH905Tv4ib5hmXpCMIPE2wzrCMttKMtJwGVJzD+URSKealG+ou+gObQSu1C96fqrfYaRj7b3uy2mzd8LA9xt0auwAgm2bLWo8Tin19Tk1vm5du3iJIDZJr5Vo6yj6aaA2SVXx8TbsuCWSvOzKK1bhuZSdDqFmNlvQYa//4Lcsf0vmkGDkAJoEJA5g1UAuFSkzMwO7ND+a8da5Cq0AGY+oncIFZMNnSU3gZfPz5y2HZ17IeT1qhlDw9gQAhJnTSXzvLShYtASxYkOKeP1PujMmlPFwbW7QYqxPJKqOt9eLvCY5Zj7wp3vq1x5SnKKEpQHnwI3odxOf39iHp4/zKAm9DhWL9vYa4QMezacqLkyDNaktMKnfyoOVMreJpDm+LS9bdfiFruCRKW/Iti62dkohGZK0ctTw20UYvAexBHbx/lk=
  on:
    branch: development
